### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by AncientLeGrey** [spine/spine.site#62]
The website http://spinejs.com is down. Please reactivate the site to make the documentation available again.

**Comment by jleft** [comment]
[The spinejs.com domain expired](https://who.is/whois/spinejs.com) on _2016-09-21_.

> | | Date |
> | --- | --- | --- |
> | Expires On | 2016-09-21 |
> | Registered On | 2011-09-21 |
> | Updated On | 2016-09-30 |


It seems the documentation is still available here though: http://maccman-spine.herokuapp.com/

**Comment by aeischeid** [comment]
working on transferring domains and that is just turning into a bit of a hassle. Hopefully resolved soon.

**Comment by cstringer** [comment]
@jleft note the documentation is available on this very site as well! https://github.com/spine/spine.site/tree/master/app/views

**Comment by aeischeid** [comment]
There was a mess with trying to get spinejs.com. and looks like someone has taken that over now and put something up... which is odd, but in the meantime I ported the old rails app to a winertsmith staticly generated site and it is hosted at http://spine.github.io/

**Comment by eliasbaixas** [comment]
Please: just update the github organization project to stop pointing to spinejs.com, its a really poor impression to someone considering using spinejs, just replace it for spine.github.io.

**Comment by aeischeid** [comment]
fixed that, thanks for pointing it out.
